### ISSUE TITLE
Can't connect via domain

### ISSUE THREAD

**Issue by atabally** [proxykingdev/x-ui#1]
I have installed certifacetes via 16 command and set SSL/TLS encryption mode to Full (strict). But still I can't connect my proxy via domain. What can be the problem?

**Comment by proxykingdev** [comment]
Does Your Domain point to your VPN server ? make sure you are not using cloudflare or other proxy for that domain or subdomain.

**Comment by atabally** [comment]
Yes it is pointed to my vpn server and I am not using any kind of proxy. When I put my IP instead of domain it is working good. When I ping my domain it gives the same IP.

**Comment by proxykingdev** [comment]
Weird. if you have updated DNS records today wait at least 24 Hours, or try it on a different device. i can't reproduce this issue

**Comment by atabally** [comment]
I found the reason why it doesn't work. Our ISP have started blocking Golang's TLS handshake :(

**Comment by proxykingdev** [comment]
Does Your Domain point to your VPN server ? make sure you are not using
cloudflare or other proxy for that domain or subdomain.
